### ISSUE TITLE
FireWall Problem

### ISSUE THREAD

**Issue by topazbor** [Kevin-Robertson/Tater#3]
I have tried Tater, and for the first time I run it, it ask for a new windows firewall rule.
And as you know, it require privileges for that.
What do you think?

![image](https://cloud.githubusercontent.com/assets/17022179/13419152/9f34126a-df84-11e5-9791-0039b6fbf309.png)

**Comment by Kevin-Robertson** [comment]
I'll test more firewall scenarios with Tater after I get Inveigh 1.1 released.

**Comment by topazbor** [comment]
maybe it will be nice to try to add arp spoffing for inveigh
thanks

**Comment by Kevin-Robertson** [comment]
I'm not sure that the firewall is blocking you in this case. In my testing, it's the NBNS spoofer that triggers the firewall alert. With default setting, the spoofer is the only thing not using 127.0.0.1. In your screenshot, I can see that WPAD has been successfully spoofed so the NBNS spoofer has done its job. Here are a few things to try:
1. Disable the firewall and see if it works
2. Enable the firewall, delete whatever you are using (powershell or powershell_ise) from the firewall allowed list and start Tater with -NBNS N. You should not see a firewall prompt. 
3. If it always hangs at that same spot, open a browser and navigate to http://127.0.0.1. You should see an HTTP request notification from Tater. This will confirm that the HTTP listener is working.
4. If the HTTP listener seems to be working, maybe try trigger 0 and just let it run for a day.
5. Try potato.exe and see if it behaves the same. https://github.com/foxglovesec/Potato

I have a couple of test systems that just don't seem to want to work anymore with either potato or tater and the Windows Defender trigger. I have not had a chance to really look into it. 

I'm going through a cleanup round with Tater and will continue to test.

**Comment by topazbor** [comment]
Great,
I will test with -NBNS N and let you know what happened
great job BTW

**Comment by topazbor** [comment]
found the problem
the firewall window pops up because of this function on the nbns spoofer
New-Object System.Net.Sockets.UdpClient(137)

this open a udp socket for listening and also pops up the firewall request window

**Comment by topazbor** [comment]
you can close this subject
